votca/buildenv

.travis.yml
fedora

add gmx builds

---

.travis.yml
ubuntu

ubuntu: initial commit

---

fedora
ubuntu

add mpi-enabled gmx

---

fedora

Part of votca/votca#29
Will need to wait for https://bodhi.fedoraproject.org/updates/FEDORA-2017-34fadcf36d

fedora: add lammps

---

.travis.yml

added gmx-2016 build

---

ubuntu

ubuntu: bump to zesty for gmx-2016

---

.travis.yml

. travis.yml: drop gmx-5.1

---

ubuntu

zesty is dead, long live artful!

ubuntu: zesty(EOL) -> artful

---

fedora
ubuntu

Needed for xtp's `eigen_linearalgebra` branch.

added libxc and ceres

---

fedora

For votca/ctp#95 and votca/votca#60

fedora: add ImageMagick for ctp-manual

---

fedora

fedora: use gnuplot-minimal

---

fedora

fedora: pick gnuplot minimal

---

fedora
ubuntu

*: add curl

---

.travis.yml
fedora

For https://github.com/votca/csg-tutorials/pull/34

fedora: adding python3-MDAnalysis for espressomd

---

fedora
ubuntu

fix https://github.com/votca/votca/issues/176

*: fix gmx install for gmx-2020

---

fedora
ubuntu

This will hopefully fix some race conditions of the gitlab runners.

*: pre-generate latex files

---

fedora

Part of https://github.com/votca/csg/issues/427

fedora: python3-cma

---

fedora
ubuntu

For https://github.com/votca/votca/issues/226

*: add ninja-build

---

fedora

For https://github.com/votca/csg/pull/511

fedora: add libomp-devel for OpenMP support

---

fedora
ubuntu

For https://github.com/votca/votca/pull/274

*: install llvm/clang devel packages

---

fedora
ubuntu

for https://github.com/votca/xtp/pull/433

*: add sphinx

---

fedora
ubuntu

For https://github.com/votca/votca/pull/277

*: added python3-recommonmark for sphinx

---

fedora

For https://github.com/votca/votca/pull/277

fedora: add python3-sphinx_rtd_theme

---

.travis.yml

Add Ubuntu:rolling image to avoid surprises like https://github.com/votca/xtp/issues/436 in the future.

.travis.yml: add ubuntu rolling

---

opensuse

for https://github.com/votca/votca/pull/288

opensuse: add more boost packages

---

fedora

For https://github.com/votca/xtp/pull/444

fedora: add kokkos-devel

---

fedora
opensuse
ubuntu

Install the [python3 nbsphinx](https://nbsphinx.readthedocs.io/en/0.7.0/) extension to automatically generate sphinx documentation from the jupyter notebooks.

Install nbsphinx

---

fedora
opensuse
ubuntu

Revert "*: re-add 'fmtutil-sys --all'"

---

fedora
opensuse
ubuntu

Running the notebooks in the CI requires `ipykernel`
Install `ipykernel`

install ipykernel

---

opensuse

For https://github.com/votca/csg/pull/549

opensuse: add libboost_regex-devel

---

fedora
opensuse

For https://github.com/votca/xtp-tutorials/pull/19

Juniper deps

---

opensuse

For https://github.com/votca/xtp-tutorials/pull/19

opensuse: install pandoc

---

fedora

For https://github.com/votca/tools/pull/283

fedora: add mkl lib to LD_LIBRARY_PATH

---

.github/workflows/continuous-integration-workflow.yml
fedora

In preparation for: https://www.docker.com/pricing/resource-consumption-updates

GHA: build for github registry as well

---

.github/workflows/continuous-integration-workflow.yml

GHA: use different packages instead of tags

---

opensuse

See https://github.com/espressomd/espresso/issues/3864 for details.

opensuse: espresso is currently broken

---

fedora

`ghcr.io` times out on big layers, error:
```
2020-09-08T21:09:23.0648611Z Successfully built dc880156d0f7
2020-09-08T21:09:23.0716836Z Successfully tagged ghcr.io/votca/buildenv/fedora:intel
2020-09-08T21:09:23.0719366Z Pushing image [ghcr.io/votca/buildenv/fedora:intel]
2020-09-08T21:09:23.2934309Z The push refers to repository [ghcr.io/votca/buildenv/fedora]
2020-09-08T21:09:23.3178988Z 40437f8311d8: Preparing
2020-09-08T21:09:23.3179272Z d5a684c011b0: Preparing
2020-09-08T21:09:23.3179432Z 1ac3dc3f3ad5: Preparing
2020-09-08T21:09:23.3179795Z 41084f6578b9: Preparing
2020-09-08T21:09:23.3179948Z c6b2d4c8f117: Preparing
2020-09-08T21:09:23.3180100Z c6028b39b268: Preparing
2020-09-08T21:09:23.3180264Z e10482b114ce: Preparing
2020-09-08T21:09:23.3180416Z a1cad8ac41b1: Preparing …
```

fedora: add intel workaround

---

fedora

Revert "fedora: add intel workaround"

---

opensuse

For https://github.com/votca/xtp/pull/559

opensuse: install libint2

---

fedora
opensuse

For https://github.com/votca/xtp/issues/567

add libecpint

---

ubuntu

For https://github.com/votca/xtp/issues/567

ubuntu: add libecpint

---

.github/workflows/continuous-integration-workflow.yml
fedora
opensuse
ubuntu

Workaround for https://github.com/votca/csg/issues/612

GMX updates

---

fedora
opensuse
ubuntu

tex and kokkos note needed after after 2021-dev was merged in `stable`.

*: remove tex and kokkos

---

fedora
ubuntu

For https://github.com/votca/xtp/pull/655

*: add python3-rdkit

---

fedora
opensuse
ubuntu

Needed for https://github.com/votca/xtp/pull/666

*: add python3-h5py

---

fedora
opensuse
ubuntu

For https://github.com/votca/xtp/pull/673

*: add pybind11

---

ubuntu

For https://github.com/votca/csg/pull/675

ubuntu: add pytest

---

fedora
opensuse

For https://github.com/votca/csg/pull/675

opensuse: add pytest

---

fedora

For https://github.com/votca/csg/pull/675

fedora: add  python3-pytest-cov for coverage build

---

.github/workflows/continuous-integration-workflow.yml

See https://github.com/actions/virtual-environments/issues/3812

CI: workaround seccomp issue

---

.github/workflows/continuous-integration-workflow.yml

Revert "CI: workaround seccomp issue"

---

.github/workflows/continuous-integration-workflow.yml

See https://github.com/kokkos/ci-containers/issues/24 for details

Build intel on F34

---

ubuntu

Fix https://github.com/votca/votca/issues/941

ubuntu: build libecpint directly

---

.github/workflows/continuous-integration-workflow.yml
fedora

Fix https://github.com/votca/votca/issues/983

CI: downgrade intel to F35

---

.github/workflows/continuous-integration-workflow.yml
ubuntu

ubuntu: clean-up libecpint install

---

fedora

For https://github.com/votca/votca/pull/997
/CC @xzhh

fedora: add espressopp

---

fedora

Workaround for https://github.com/votca/votca/issues/1009

fedora: disable espresso++ build

---

fedora
opensuse

Revert "fedora: remove lammps for now"

---

.github/workflows/continuous-integration-workflow.yml

Reverts votca/buildenv#195
F38 works now....

Revert "CI: try F37 for intel build"

---

.github/workflows/continuous-integration-workflow.yml

Using F37 for intel again

---

fedora

fedora: export CMPLR_ROOT for Intel

---

.github/workflows/continuous-integration-workflow.yml
fedora

Reverts votca/buildenv#208
https://github.com/votca/votca/pull/1109#pullrequestreview-1883655092

Revert "fedora: add v2019.6 container"
