- fedora
- ubuntu
Hopefully, this fixes the **illegal instruction** error, when running `csg_* --help` (as part of the build) on travis.
> compile gromacs with SSE2 only

- fedora
Workaround for https://github.com/votca/tools/issues/85, but we need to wait for https://bodhi.fedoraproject.org/updates/FEDORA-2018-5905fb6984.
Fix https://github.com/votca/tools/issues/85
> fedora: install eigen-3.3.5 for now

- fedora
- ubuntu
Workaround for https://github.com/codecov/codecov-bash/pull/164, revert when merged.
> *: install our patched version of codecov

- fedora
Reverts votca/buildenv#35
Pymol is dead on Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1675704
> Revert "fedora: add pymol as well"

- fedora
- ubuntu
This reverts commit 286eec7395daa3c27125754d826a96057df8c3ee (part of #31).
Upstream issue (https://github.com/codecov/codecov-bash/pull/164) has been fixed.
> Revert "*: codecov fix got moved to votca"

- fedora
- opensuse
- ubuntu
Github actions uses:
```
uid=1001(runner) gid=116(docker) groups=116(docker),4(adm),101(systemd-journal)
```
as user, but our containers have:
```
uid=1000(votca) gid=1000(votca) groups=1000(votca),10(wheel)
```
which leads to permission problem when mounting the files system from the outside.
As we cannot really change all file permission let's just try to make the uids the same.
> *: use github action user id

- opensuse
https://build.opensuse.org/request/show/800834 is done, so we can enable kokkos on opensuse.
> opensuse: add kokkos-devel

- .github/workflows/continuous-integration-workflow.yml
- actions
`votca/actions/setup` only uses bash and git, so this new container will avoid pulling our 3GB standard buildenv container.
> add tiny container for votca/actions

- opensuse
- ubuntu
We only build sphinx on Fedora or let's remove the unneeded packages.
> opensuse,ubuntu: remove sphinx deps

- .github/workflows/continuous-integration-workflow.yml
This reverts commit 0f8106db6a7e81a8c9fb92ff620031ec50692646.
Was part of #132
> Revert "GHA: used gmx's 3288-fileio instead of master for now"

- .github/workflows/continuous-integration-workflow.yml
- ubuntu
Reverts votca/buildenv#134
New buildx times out a lot when pushing:
```
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed commit on ref "layer-sha256:49507e21bb5d0cee4bce2fee3248063d1eff846974de5da2d70f7edc07af9181": no response
```
so reverting to v1 for now.
https://github.com/docker/build-push-action/issues/251
> Revert "GHA: use docker v2 action"

- .github/workflows/continuous-integration-workflow.yml
Debug using https://github.com/docker/build-push-action/issues/251#issuecomment-742976840
> Docker v2: second try

- .github/workflows/continuous-integration-workflow.yml
- ubuntu
Now as stable is update to 2021-dev, we don't need the ubuntu 18.04 container anymore.
Note to self: remove `18.04` tag from https://github.com/orgs/votca/packages/container/package/buildenv%2Fubuntu after this is merged.
> ubuntu: rm 18.04 build

- ubuntu
For https://github.com/votca/xtp/pull/588
> ubuntu: force using newest libecpint version

- .github/workflows/continuous-integration-workflow.yml
Reverts votca/buildenv#166
Works with "options: --security-opt seccomp=unconfined"
> Revert "Revert "CI: workaround seccomp issue""

- fedora
Reverts votca/buildenv#185
Fix https://github.com/votca/votca/issues/1009 for now.
> fedora: re-enable espresso++ build

- .github/workflows/continuous-integration-workflow.yml
- fedora
- opensuse
- ubuntu
Hi @junghans , 
Together with @baumeier we are preparing a PR to votca that will add a python interface for xtp based on an ASE calculator. For Votca's CI to pass we need two extra dependencies: xmltodict that is used for the option's handling of the calculator and ASE itself.
This PR adds xmltodict and ase to the different OS. I think the name of the packaged for openSuse and Fedora are correct but I'm not 100% sure.
Best
Nico
> added new packages required for the ase calculator

- opensuse
It seems the lammps version on openSUSE is broken.
/CC @rbberger
> opensuse: remove lammps again

- .github/workflows/continuous-integration-workflow.yml
- fedora
Dropped in F34, pip fails on rawhide (F40)
> fedora: remove rdkit

- opensuse
Undo once https://github.com/espressomd/espresso/issues/4856 is fixed.
> opensuse: drop python3-espressomd for now

- opensuse
Reverts votca/buildenv#206
Merge once https://build.opensuse.org/request/show/1144047 is done.
> Revert "opensuse: drop python3-espressomd for now"

- fedora
> fedora: drop intel classic compiler

- fedora
> fedora: fix intel paths

- .github/workflows/continuous-integration-workflow.yml
- fedora
For https://github.com/votca/votca/pull/1164
> CI: add arm64 builds
